[GENERAL]
bulkdataname = oracle-cards.json
excludesets = funny, memorabilia, minigame, alchemy, tokens
excludelayouts = token, emblem, art_series, double_faced_token, scheme, planar, phenomenon, vanguard, augment, host, meld
pseudodoublefacedlayouts = adventure, omen, flip, prepare
requiregames = paper
requiretypes = creature
excludeplaytest = true

#Project relative path to save images to. Must end with a slash.
imagepath = Images/
imagetype = png 

#Options are "soft" and "hard". "soft" will only delete images for cards that are no longer eligible. "hard" will delete all images.
deletetype = soft
#Set to True to enable verbose logging during parsing.
verboselogging = false
 #Set to False to skip validation of card data against the Scryfall API. Not recommended.
validatedata = true

[GPIO]
button1pin = 17
button2pin = 27
button3pin = 22
buttonbouncetime = 0.05