[GENERAL]
bulk_data_name = oracle-cards.json
exclude_sets = funny, memorabilia, minigame, alchemy, tokens
exclude_layouts = token, emblem, art_series, double_faced_token, scheme, planar, phenomenon, vanguard, augment, host, meld
pseudo_double_faced_layouts = adventure, omen, flip, prepare
require_games = paper
require_types = creature
exclude_playtest = true

#Project relative path to save images to. Must end with a slash.
image_path = Images/
image_type = png

#Set to True to enable verbose logging during parsing.
verbose_logging = false

[GPIO]
up_button_pin = 17
down_button_pin = 27
enter_button_pin = 22
button_bounce_time = 0.05